// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlUZaghUvp0OSayMgnYisIoSlAzKUBSAQ',
    appId: '1:29623966317:web:cc9354992e7cda94667d64',
    messagingSenderId: '29623966317',
    projectId: 'nsspuridelegate',
    authDomain: 'nsspuridelegate.firebaseapp.com',
    storageBucket: 'nsspuridelegate.appspot.com',
    measurementId: 'G-N6D6GGLWZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj1S-MDZQIHnkt9sCDX5rhHaJEYrdk7qI',
    appId: '1:29623966317:android:b7a0038aadff4e4d667d64',
    messagingSenderId: '29623966317',
    projectId: 'nsspuridelegate',
    storageBucket: 'nsspuridelegate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnt6vD1k3Qh51wElUMZT46DS67E-XcELg',
    appId: '1:29623966317:ios:51e22916ad239651667d64',
    messagingSenderId: '29623966317',
    projectId: 'nsspuridelegate',
    storageBucket: 'nsspuridelegate.appspot.com',
    iosBundleId: 'com.example.sammilaniDelegate',
  );
}
