class SanghaList {
  static final List<String> sangha = [
    'Anugul Sakha Sangha',
    'Bikrampur Sakha Sangha',
    'Jagannathpur Sakha Sangha',
    'Talcher Town Sakha Sangha',
    'Nalco Sakha Sangha',
    'Rankasingha Sakha Sangha',
    'Samal Byarej Sakha Sangha',
    'NTPC Sakha Sangha',
    'Athamalik Sakha Sangha',
    'Asureswar Sakha Sangha',
    'Jobra Sakha Sangha',
    'Kamarpada Sakha Sangha',
    'Narasingpur Sakha Sangha',
    'Kendupatana Sakha Sangha',
    'Kurunti Sakha Sangha',
    'Bailaish Mouja Sakha Sangha',
    'Choudwar Sakha Sangha',
    'Tangi Sakha Sangha',
    'Badamba Sakha Sangha',
    'Barapada Sakha Sangha',
    'Sukarapada Sakha Sangha',
    'Niali Sakha Sangha',
    'Gopalpur Sakha Sangha',
    'Athagada Sakha Sangha',
    'Banki Sakha Sangha',
    'Khalarda Sakha Sangha',
    'Bachhasailo Sakha Sangha',
    'Endulapur Sakha Sangha',
    'Oupada Sakha Sangha',
    'Kaetha Sakha Sangha',
    'Katana Sakha Sangha',
    'Chandiagadhi Sakha Sangha',
    'Kurunti Sakha Sangha',
    'Gopei Sakha Sangha',
    'Gouda gaa Sakha Sangha',
    'Chhachina Sakha Sangha',
    'Jarimula Sakha Sangha',
    'Junapangara Sakha Sangha',
    'Tikhiri Sakha Sangha',
    'TULASHIKHETRA Sakha Sangha',
    'DEULAPADA Sakha Sangha',
    'NADIA BAREI Sakha Sangha',
    'NAUKANA Sakha Sangha',
    'RAJNAGAR Sakha Sangha',
    'NARAHARIPUR Sakha Sangha',
    'ADHANGA Sakha Sangha',
    'BIJAY NAGAR Sakha Sangha',
    'NUAGAA Sakha Sangha',
    'MATIA Sakha Sangha',
    'BASUDEIPUR Sakha Sangha',
    'MAHARA SAI Sakha Sangha',
    'BILIKANA Sakha Sangha',
    'MAHAKALAPADA Sakha Sangha',
    'MANDAPADA Sakha Sangha',
    'RAHAMA Sakha Sangha',
    'RAJKANIKA Sakha Sangha',
    'RAJPUR Sakha Sangha',
    'RAMNAGAR Sakha Sangha',
    'NIALA Sakha Sangha',
    'SINGHAPAHAR Sakha Sangha',
    'JAYPORE  Sakha Sangha',
    'DAMANJODI Sakha Sangha',
    'SIMILIGUDA Sakha Sangha',
    'BALIMELA Sakha Sangha',
    'KENDRA SEBAK SANGHA',
    'RAJDHANI TOWN Sakha Sangha',
    'ATRI Sakha Sangha',
    'EKAMRA Sakha Sangha',
    'BANAMALIPUR Sakha Sangha',
    'BEGUNIA Sakha Sangha',
    'KHORDA Sakha Sangha',
    'BOLAGADA Sakha Sangha',
    'SANAPADAR Sakha Sangha',
    'LANJIA Sakha Sangha',
    'BADAKHETA Sakha Sangha',
    'TANARADA Sakha Sangha',
    'SIDHARTHA NAGAR Sakha Sangha',
    'BADAMUNDILO Sakha Sangha',
    'JAGATSINGHPUR Sakha Sangha',
    'RAHAMA Sakha Sangha',
    'DARADA PATANA Sakha Sangha',
    'NAUGAA Sakha Sangha',
    'NAUBAZAR, PARADIP Sakha Sangha',
    'ERASAMA Sakha Sangha',
    'HALADIPANI Sakha Sangha',
    'PARALAKHEMUNDI Sakha Sangha',
    'JHARSUGUDA TOWN Sakha Sangha',
    'RASOLA Sakha Sangha',
    'KAMAKSHYA NAGAR Sakha Sangha',
    'DHENKANAL Sakha Sangha',
    'BALIKIARI Sakha Sangha',
    'KANDAR SINGHA Sakha Sangha',
    'INDRABATI Sakha Sangha',
    'NAYAGARH Sakha Sangha',
    'THUABARI Sakha Sangha',
    'RANIMUNDA Sakha Sangha',
    'KHADIALA Sakha Sangha',
    'DUAJHAR Sakha Sangha',
    'BALIGUDA Sakha Sangha',
    'PHULBANI Sakha Sangha',
    'BARAGADA Sakha Sangha',
    'NIMAPADA Sakha Sangha',
    'PURI TOWN Sakha Sangha',
    'BALANGIR Sakha Sangha',
    'SILANDA Sakha Sangha',
    'RAIBANIA Sakha Sangha',
    'KUAGADIA Sakha Sangha',
    'KUPARI Sakha Sangha',
    'GARASANGA Sakha Sangha',
    'NILAGIRI Sakha Sangha',
    'ANTARA Sakha Sangha',
    'CHITOLA Sakha Sangha',
    'DANTIA Sakha Sangha',
    'GOOD Sakha Sangha',
    'BALABHADRAPUR Sakha Sangha',
    'MAHATIPUR Sakha Sangha',
    'SORO Sakha Sangha',
    'BARAPADA Sakha Sangha',
    'MUKTESWARPUR Sakha Sangha',
    'FATEPUR Sakha Sangha',
    'GOPINATHPUR Sakha Sangha',
    'DANDI Sakha Sangha',
    'BAINANDA Sakha Sangha',
    'BALASORE Sakha Sangha',
    'MATIGADA Sakha Sangha',
    'DHUSHULI Sakha Sangha',
    'JALAHARI Sakha Sangha',
    'DHUSHURI Sakha Sangha',
    'ARADI Sakha Sangha',
    'KHADIMAHARA Sakha Sangha',
    'BETADA Sakha Sangha',
    'BASUDEBPUR Sakha Sangha',
    'PALIABINDHA Sakha Sangha',
    'GOBINDPUR Sakha Sangha',
    'PALIABINDHA Sakha Sangha',
    'BHADRAK Sakha Sangha',
    'BANIDIA Sakha Sangha',
    'BACHHADA Sakha Sangha',
    'PANDUPANI Sakha Sangha',
    'BARIPADA Sakha Sangha',
    'KUNDAPATANA Sakha Sangha',
    'DHARMASHALA Sakha Sangha',
    'SOBRA Sakha Sangha',
    'KALAKALA Sakha Sangha',
    'KANTIGADIA Sakha Sangha',
    'BYASANAGAR Sakha Sangha',
    'JAJPUR TOWN Sakha Sangha',
    'KABATABANDHA Sakha Sangha',
    'DEKUDI, PALLI Sakha Sangha',
    'KUAKHIA Sakha Sangha',
    'SAMBALPUR Sakha Sangha',
    'FASHIMALA Sakha Sangha',
    'BURLA Sakha Sangha',
    'BARAGADA Sakha Sangha',
    'RAJGANGPUR Sakha Sangha',
    'ROURKELA TOWN Sakha Sangha',
    'SHAKTI NAGAR, ROURKELA Sakha Sangha',
    'BALIJODI Sakha Sangha',
    'DENGIBHADI Sakha Sangha',
    'KENDUJHAR Sakha Sangha',
    'JODA Sakha Sangha',
    'ANANDAPUR akha Sangha',
    'ATASAHI Sakha Sangha',
    'SALABANI Sakha Sangha',
    'CHENNAPADI Sakha Sangha',
    'BOUDHA Sakha Sangha',
    'America Saraswata ',
    'Mumbai Saraswata Sangha',
    'Karnataka Saraswata Sangha',
    'Pune Saraswata Sangha',
    'Delhi Saraswata Sangha',
    'Chennai Sakha Sangha',
    'Kolkata Saraswata Sangha',
    'Surat Shakha Sangha',
    'Hyderabad Saraswata Sangha',
    'Jamshedpur Sakha Sangha',
    'Rishikesh Ashram',
    'Raipur Sakha sangha',
    'Ranchi Pathachakra',
    'Allahabad Pathachakra',
    'Ahmedabad Pathachakra',
    'Faridabad Pathachakra',
    'Ghaziabad Pathachakra',
    'Guwahati Pathachakra',
    'Europe Pathachakra',
    'Nigeria Pathachakra',
  ];

  static List<String> getSuggestions(String query) {
    List<String> matches = [];
    matches.addAll(sangha);
    matches.retainWhere((s) => s.toLowerCase().contains(query.toLowerCase()));
    return matches;
  }
}
